export const siteConfig = {
  name: 'Liddell Stor-It',
  parentName: 'Liddell Stor All',
  url: 'https://liddellstorit.com',
  reserveUrl: 'https://www.liddellstorall.com/pages/storit',
  aboutUrl: 'https://www.liddellstorall.com/pages/about-us',
  contactUrl: 'https://www.liddellstorall.com/pages/contact',
  phone: '8702369391',
  formattedPhone: '(870) 236-9391',
  email: 'storage@liddellstorall.com',
  address: {
    streetAddress: '1300 Country Club Rd',
    addressLocality: 'Paragould',
    addressRegion: 'AR',
    postalCode: '72450',
    addressCountry: 'US',
  },
  serviceArea: [
    'Northeast Arkansas',
    'Paragould, Arkansas (Greene County)',
    'Jonesboro, Arkansas (Craighead County)',
    'West Memphis, Arkansas (Crittenden County)',
    'Memphis, Tennessee (Shelby County)',
    'Bartlett, Tennessee (Shelby County)',
    'Southaven, Mississippi (DeSoto County)',
    'Collierville, Tennessee (Shelby County)',
    'Germantown, Tennessee (Shelby County)',
    'Olive Branch, Mississippi (DeSoto County)',
    'Horn Lake, Mississippi (DeSoto County)',
    'Poplar Bluff, Missouri (Butler County)',
  ],
  deliveryZone: {
    radiusMiles: 20,
    feeWithinRadius: 90,
  },
  hours: [
    { day: 'Monday', opens: '09:00', closes: '17:00' },
    { day: 'Tuesday', opens: '09:00', closes: '17:00' },
    { day: 'Wednesday', opens: '09:00', closes: '17:00' },
    { day: 'Thursday', opens: '09:00', closes: '17:00' },
    { day: 'Friday', opens: '09:00', closes: '17:00' },
  ],
  containerOffers: [
    {
      name: 'Portable Container (8 x 16 x 8)',
      size: "8' x 16' x 8'",
      monthlyRent: 195,
      reservationDeposit: 50,
      deliveryFee: 90,
      pickupFee: 90,
      relocationFee: 90,
      availability: 'InStock',
      description: 'Compact portable storage container for smaller moves, apartment loads, seasonal items, and a few rooms of furniture.',
    },
    {
      name: 'Portable Container (8 x 20 x 8)',
      size: "8' x 20' x 8'",
      monthlyRent: 225,
      reservationDeposit: 75,
      deliveryFee: 90,
      pickupFee: 90,
      relocationFee: 90,
      availability: 'InStock',
      description: 'Larger portable storage container for whole-home moves, remodels, bulky furniture, and extra project room.',
    },
  ],
} as const

export const contentFreshnessDate = '2026-04-17'

/**
 * Service-area pages carry their own freshness date because they are revised
 * independently of the guides and marketing pages. Bump this when the
 * serviceAreas data or the service-area template changes.
 */
export const serviceAreaFreshnessDate = '2026-07-27'

export const navLinks = [
  { href: '/', label: 'Home' },
  { href: '/guides', label: 'Guides' },
  { href: '/service-areas', label: 'Service Areas' },
  { href: '/faq', label: 'FAQ' },
] as const

export const guides = [
  {
    slug: 'how-to-pack-a-storage-container',
    title: 'How to Pack a Storage Container',
    description: 'A practical packing order for keeping items safe, accessible, and organized during a move or renovation.',
    updatedAt: '2026-04-17',
  },
  {
    slug: 'choosing-the-right-container-size',
    title: 'Choosing the Right Container Size',
    description: 'A simple way to estimate how much space you need for a home, apartment, or business project.',
    updatedAt: '2026-04-17',
  },
  {
    slug: 'storage-container-pricing',
    title: 'Storage Container Pricing Explained',
    description: 'For up-to-date pricing, refer to our <a href="{{reserveUrl}}">Reservation Page</a>. This guide explains what affects portable storage pricing and how to compare quotes without surprises.',
    updatedAt: '2026-04-17',
  },
  {
    slug: 'moving-tips',
    title: 'Moving Tips',
    description: 'A practical moving pillar page with timeline advice, packing priorities, and ways to stay organized before moving day.',
    updatedAt: '2026-04-17',
  },
  {
    slug: 'home-organization',
    title: 'Home Organization',
    description: 'Ideas for decluttering, seasonal storage, and getting rooms back under control without feeling overwhelmed.',
    updatedAt: '2026-04-17',
  },
  {
    slug: 'renovation-planning',
    title: 'Renovation Planning',
    description: 'Advice for staging rooms, protecting furniture, and planning storage around remodel timelines.',
    updatedAt: '2026-04-17',
  },
  {
    slug: 'moving-tips/move-day-checklist',
    title: 'Move-Day Checklist',
    description: 'A simple checklist for the last 24 hours before moving day so nothing gets missed.',
    updatedAt: '2026-04-17',
  },
  {
    slug: 'moving-tips/how-to-pack-fragile-items',
    title: 'How to Pack Fragile Items',
    description: 'A practical guide to wrapping, labeling, and loading breakables so they stay protected.',
    updatedAt: '2026-04-17',
  },
  {
    slug: 'moving-tips/how-to-load-a-storage-container',
    title: 'How to Load a Storage Container',
    description: 'Tips for stacking heavier items first, keeping weight balanced, and leaving room where needed.',
    updatedAt: '2026-04-17',
  },
  {
    slug: 'home-organization/decluttering-by-room',
    title: 'Decluttering by Room',
    description: 'A room-by-room approach to clearing clutter without trying to organize the whole house at once.',
    updatedAt: '2026-04-17',
  },
  {
    slug: 'home-organization/garage-organization',
    title: 'Garage Organization',
    description: 'How to make garage space more usable with better sorting, storage, and seasonal rotation.',
    updatedAt: '2026-04-17',
  },
  {
    slug: 'home-organization/seasonal-storage',
    title: 'Seasonal Storage',
    description: 'A guide to storing holiday decor, patio gear, and off-season items without creating clutter.',
    updatedAt: '2026-04-17',
  },
  {
    slug: 'renovation-planning/pre-renovation-timeline',
    title: 'Pre-Renovation Timeline',
    description: 'A planning timeline that helps you clear rooms and reserve storage before remodeling starts.',
    updatedAt: '2026-04-17',
  },
  {
    slug: 'renovation-planning/how-to-protect-furniture-during-remodel',
    title: 'How to Protect Furniture During a Remodel',
    description: 'Steps for keeping furniture clean, safe, and out of the work zone during renovation projects.',
    updatedAt: '2026-04-17',
  },
  {
    slug: 'renovation-planning/contractor-staging-plan',
    title: 'Contractor Staging Plan',
    description: 'How to stage rooms so contractors can move efficiently and the project stays organized.',
    updatedAt: '2026-04-17',
  },
] as const

export type ServiceArea = {
  slug: string
  title: string
  description: string
  city?: string
  state?: string
  county?: string
  /** Driving distance in miles from the Paragould yard (OSRM, road route). */
  roadMiles?: number
  /** Typical driving time in minutes from the Paragould yard. */
  driveMinutes?: number
  /** Slugs of the closest other service areas, nearest first. */
  nearby?: readonly string[]
}

export const serviceAreas: readonly ServiceArea[] = [
  {
    slug: 'northeast-arkansas',
    title: 'Northeast Arkansas',
    description: 'Portable storage for moves, remodels, and cleanup projects across Northeast Arkansas communities.',
  },
  {
    slug: 'paragould-ar',
    title: 'Paragould, AR (Greene County)',
    description: 'Fast local delivery, flexible rental periods, and simple pickup for homes and businesses in Paragould.',
    city: 'Paragould',
    state: 'AR',
    county: 'Greene County',
    roadMiles: 2,
    driveMinutes: 4,
    nearby: ['marmaduke-ar', 'cardwell-mo', 'brookland-ar', 'monette-ar'],
  },
  {
    slug: 'jonesboro-ar',
    title: 'Jonesboro, AR (Craighead County)',
    description: 'Portable storage for moves, cleanouts, and remodels in Jonesboro and Craighead County.',
    city: 'Jonesboro',
    state: 'AR',
    county: 'Craighead County',
    roadMiles: 23,
    driveMinutes: 37,
    nearby: ['bono-ar', 'brookland-ar', 'cash-ar', 'lake-city-ar'],
  },
  {
    slug: 'west-memphis-ar',
    title: 'West Memphis, AR (Crittenden County)',
    description: 'Local delivery and pickup for portable storage projects in West Memphis and nearby Crittenden County communities.',
    city: 'West Memphis',
    state: 'AR',
    county: 'Crittenden County',
    roadMiles: 79,
    driveMinutes: 99,
    nearby: ['memphis-tn', 'southaven-ms', 'horn-lake-ms', 'bartlett-tn'],
  },
  {
    slug: 'memphis-tn',
    title: 'Memphis, TN (Shelby County)',
    description: 'Portable storage delivery for homes, renovations, and business projects across Memphis and Shelby County.',
    city: 'Memphis',
    state: 'TN',
    county: 'Shelby County',
    roadMiles: 86,
    driveMinutes: 106,
    nearby: ['west-memphis-ar', 'bartlett-tn', 'southaven-ms', 'horn-lake-ms'],
  },
  {
    slug: 'bartlett-tn',
    title: 'Bartlett, TN (Shelby County)',
    description: 'Flexible container delivery for household projects, business overflow, and renovations in Bartlett.',
    city: 'Bartlett',
    state: 'TN',
    county: 'Shelby County',
    roadMiles: 98,
    driveMinutes: 125,
    nearby: ['germantown-tn', 'memphis-tn', 'collierville-tn', 'southaven-ms'],
  },
  {
    slug: 'southaven-ms',
    title: 'Southaven, MS (DeSoto County)',
    description: 'Portable storage for moves and remodels in Southaven and the surrounding DeSoto County area.',
    city: 'Southaven',
    state: 'MS',
    county: 'DeSoto County',
    roadMiles: 97,
    driveMinutes: 121,
    nearby: ['horn-lake-ms', 'olive-branch-ms', 'memphis-tn', 'germantown-tn'],
  },
  {
    slug: 'collierville-tn',
    title: 'Collierville, TN (Shelby County)',
    description: 'Convenient storage container delivery for homes and businesses in Collierville.',
    city: 'Collierville',
    state: 'TN',
    county: 'Shelby County',
    roadMiles: 115,
    driveMinutes: 146,
    nearby: ['germantown-tn', 'olive-branch-ms', 'bartlett-tn', 'southaven-ms'],
  },
  {
    slug: 'germantown-tn',
    title: 'Germantown, TN (Shelby County)',
    description: 'Portable storage for cleanouts, moves, and renovation projects in Germantown.',
    city: 'Germantown',
    state: 'TN',
    county: 'Shelby County',
    roadMiles: 100,
    driveMinutes: 134,
    nearby: ['olive-branch-ms', 'collierville-tn', 'bartlett-tn', 'southaven-ms'],
  },
  {
    slug: 'olive-branch-ms',
    title: 'Olive Branch, MS (DeSoto County)',
    description: 'Reliable container delivery for homeowners, contractors, and businesses in Olive Branch.',
    city: 'Olive Branch',
    state: 'MS',
    county: 'DeSoto County',
    roadMiles: 105,
    driveMinutes: 135,
    nearby: ['germantown-tn', 'southaven-ms', 'collierville-tn', 'horn-lake-ms'],
  },
  {
    slug: 'horn-lake-ms',
    title: 'Horn Lake, MS (DeSoto County)',
    description: 'Portable storage options for short-term moves, remodels, and extra space in Horn Lake.',
    city: 'Horn Lake',
    state: 'MS',
    county: 'DeSoto County',
    roadMiles: 101,
    driveMinutes: 127,
    nearby: ['southaven-ms', 'olive-branch-ms', 'memphis-tn', 'germantown-tn'],
  },
  {
    slug: 'poplar-bluff-mo',
    title: 'Poplar Bluff, MO (Butler County)',
    description: 'Portable storage delivery for moves, renovations, and business storage projects in Poplar Bluff.',
    city: 'Poplar Bluff',
    state: 'MO',
    county: 'Butler County',
    roadMiles: 58,
    driveMinutes: 79,
    nearby: ['dexter-mo', 'corning-ar', 'piggott-ar', 'holcomb-mo'],
  },
  {
    slug: 'bono-ar',
    title: 'Bono, AR (Craighead County)',
    description: 'Portable storage for moves, renovations, and cleanup projects in Bono and nearby Craighead County areas.',
    city: 'Bono',
    state: 'AR',
    county: 'Craighead County',
    roadMiles: 31,
    driveMinutes: 46,
    nearby: ['jonesboro-ar', 'cash-ar', 'brookland-ar', 'walnut-ridge-ar'],
  },
  {
    slug: 'brookland-ar',
    title: 'Brookland, AR (Craighead County)',
    description: 'Local portable storage delivery for homes and projects in Brookland.',
    city: 'Brookland',
    state: 'AR',
    county: 'Craighead County',
    roadMiles: 14,
    driveMinutes: 22,
    nearby: ['jonesboro-ar', 'lake-city-ar', 'paragould-ar', 'bono-ar'],
  },
  {
    slug: 'marmaduke-ar',
    title: 'Marmaduke, AR (Greene County)',
    description: 'Portable storage for moves and remodels in Marmaduke and surrounding Greene County communities.',
    city: 'Marmaduke',
    state: 'AR',
    county: 'Greene County',
    roadMiles: 11,
    driveMinutes: 17,
    nearby: ['rector-ar', 'cardwell-mo', 'paragould-ar', 'senath-mo'],
  },
  {
    slug: 'rector-ar',
    title: 'Rector, AR (Clay County)',
    description: 'Portable storage delivery for household and business projects in Rector.',
    city: 'Rector',
    state: 'AR',
    county: 'Clay County',
    roadMiles: 18,
    driveMinutes: 28,
    nearby: ['marmaduke-ar', 'piggott-ar', 'senath-mo', 'kennett-mo'],
  },
  {
    slug: 'piggott-ar',
    title: 'Piggott, AR (Clay County)',
    description: 'Portable storage options for moves, storage overflow, and renovation projects in Piggott.',
    city: 'Piggott',
    state: 'AR',
    county: 'Clay County',
    roadMiles: 32,
    driveMinutes: 48,
    nearby: ['holcomb-mo', 'rector-ar', 'kennett-mo', 'senath-mo'],
  },
  {
    slug: 'delaplaine-ar',
    title: 'Delaplaine, AR (Greene County)',
    description: 'Convenient container delivery for homes and projects in Delaplaine.',
    city: 'Delaplaine',
    state: 'AR',
    county: 'Greene County',
    roadMiles: 22,
    driveMinutes: 38,
    nearby: ['pocahontas-ar', 'corning-ar', 'maynard-ar', 'walnut-ridge-ar'],
  },
  {
    slug: 'walnut-ridge-ar',
    title: 'Walnut Ridge, AR (Lawrence County)',
    description: 'Portable storage delivery for moves, cleanouts, and remodels in Walnut Ridge.',
    city: 'Walnut Ridge',
    state: 'AR',
    county: 'Lawrence County',
    roadMiles: 27,
    driveMinutes: 34,
    nearby: ['pocahontas-ar', 'bono-ar', 'imboden-ar', 'delaplaine-ar'],
  },
  {
    slug: 'pocahontas-ar',
    title: 'Pocahontas, AR (Randolph County)',
    description: 'Portable storage for homeowners, contractors, and businesses in Pocahontas.',
    city: 'Pocahontas',
    state: 'AR',
    county: 'Randolph County',
    roadMiles: 40,
    driveMinutes: 49,
    nearby: ['maynard-ar', 'imboden-ar', 'walnut-ridge-ar', 'delaplaine-ar'],
  },
  {
    slug: 'swifton-ar',
    title: 'Swifton, AR (Jackson County)',
    description: 'Container delivery for short-term moves, renovations, and extra storage in Swifton.',
    city: 'Swifton',
    state: 'AR',
    county: 'Jackson County',
    roadMiles: 50,
    driveMinutes: 66,
    nearby: ['cash-ar', 'newport-ar', 'bono-ar', 'walnut-ridge-ar'],
  },
  {
    slug: 'cash-ar',
    title: 'Cash, AR (Craighead County)',
    description: 'Portable storage delivery for household projects and renovations in Cash.',
    city: 'Cash',
    state: 'AR',
    county: 'Craighead County',
    roadMiles: 39,
    driveMinutes: 56,
    nearby: ['bono-ar', 'swifton-ar', 'jonesboro-ar', 'walnut-ridge-ar'],
  },
  {
    slug: 'harrisburg-ar',
    title: 'Harrisburg, AR (Poinsett County)',
    description: 'Portable storage support for moves, storage overflow, and cleanup projects in Harrisburg.',
    city: 'Harrisburg',
    state: 'AR',
    county: 'Poinsett County',
    roadMiles: 40,
    driveMinutes: 63,
    nearby: ['trumann-ar', 'marked-tree-ar', 'jonesboro-ar', 'cash-ar'],
  },
  {
    slug: 'trumann-ar',
    title: 'Trumann, AR (Poinsett County)',
    description: 'Portable storage delivery for homes and businesses in Trumann.',
    city: 'Trumann',
    state: 'AR',
    county: 'Poinsett County',
    roadMiles: 35,
    driveMinutes: 55,
    nearby: ['lepanto-ar', 'lake-city-ar', 'marked-tree-ar', 'harrisburg-ar'],
  },
  {
    slug: 'lake-city-ar',
    title: 'Lake City, AR (Craighead County)',
    description: 'Portable container delivery for projects in Lake City and nearby areas.',
    city: 'Lake City',
    state: 'AR',
    county: 'Craighead County',
    roadMiles: 23,
    driveMinutes: 40,
    nearby: ['monette-ar', 'brookland-ar', 'trumann-ar', 'leachville-ar'],
  },
  {
    slug: 'monette-ar',
    title: 'Monette, AR (Craighead County)',
    description: 'Portable storage for moves, remodels, and extra space in Monette.',
    city: 'Monette',
    state: 'AR',
    county: 'Craighead County',
    roadMiles: 22,
    driveMinutes: 36,
    nearby: ['leachville-ar', 'lake-city-ar', 'cardwell-mo', 'brookland-ar'],
  },
  {
    slug: 'leachville-ar',
    title: 'Leachville, AR (Mississippi County)',
    description: 'Portable storage options for Leachville homes, remodels, and business projects.',
    city: 'Leachville',
    state: 'AR',
    county: 'Mississippi County',
    roadMiles: 23,
    driveMinutes: 34,
    nearby: ['monette-ar', 'cardwell-mo', 'lake-city-ar', 'senath-mo'],
  },
  {
    slug: 'cardwell-mo',
    title: 'Cardwell, MO (Dunklin County)',
    description: 'Convenient portable storage delivery for projects in Cardwell.',
    city: 'Cardwell',
    state: 'MO',
    county: 'Dunklin County',
    roadMiles: 14,
    driveMinutes: 19,
    nearby: ['leachville-ar', 'senath-mo', 'marmaduke-ar', 'monette-ar'],
  },
  {
    slug: 'lepanto-ar',
    title: 'Lepanto, AR (Poinsett County)',
    description: 'Portable storage for moves, renovations, and cleanup jobs in Lepanto.',
    city: 'Lepanto',
    state: 'AR',
    county: 'Poinsett County',
    roadMiles: 47,
    driveMinutes: 78,
    nearby: ['marked-tree-ar', 'trumann-ar', 'lake-city-ar', 'monette-ar'],
  },
  {
    slug: 'marked-tree-ar',
    title: 'Marked Tree, AR (Poinsett County)',
    description: 'Local container delivery for homes and businesses in Marked Tree.',
    city: 'Marked Tree',
    state: 'AR',
    county: 'Poinsett County',
    roadMiles: 48,
    driveMinutes: 66,
    nearby: ['lepanto-ar', 'trumann-ar', 'harrisburg-ar', 'lake-city-ar'],
  },
  {
    slug: 'senath-mo',
    title: 'Senath, MO (Dunklin County)',
    description: 'Portable storage delivery for moving and remodeling projects in Senath.',
    city: 'Senath',
    state: 'MO',
    county: 'Dunklin County',
    roadMiles: 23,
    driveMinutes: 31,
    nearby: ['kennett-mo', 'cardwell-mo', 'rector-ar', 'marmaduke-ar'],
  },
  {
    slug: 'kennett-mo',
    title: 'Kennett, MO (Dunklin County)',
    description: 'Portable storage for residential and commercial projects in Kennett.',
    city: 'Kennett',
    state: 'MO',
    county: 'Dunklin County',
    roadMiles: 33,
    driveMinutes: 41,
    nearby: ['senath-mo', 'holcomb-mo', 'piggott-ar', 'rector-ar'],
  },
  {
    slug: 'holcomb-mo',
    title: 'Holcomb, MO (Dunklin County)',
    description: 'Portable storage delivery for moves, cleanouts, and renovation projects in Holcomb.',
    city: 'Holcomb',
    state: 'MO',
    county: 'Dunklin County',
    roadMiles: 46,
    driveMinutes: 60,
    nearby: ['piggott-ar', 'kennett-mo', 'rector-ar', 'senath-mo'],
  },
  {
    slug: 'dexter-mo',
    title: 'Dexter, MO (Stoddard County)',
    description: 'Portable storage options for homes and businesses in Dexter.',
    city: 'Dexter',
    state: 'MO',
    county: 'Stoddard County',
    roadMiles: 76,
    driveMinutes: 105,
    nearby: ['poplar-bluff-mo', 'holcomb-mo', 'piggott-ar', 'kennett-mo'],
  },
  {
    slug: 'highland-ar',
    title: 'Highland, AR (Sharp County)',
    description: 'Convenient portable storage for projects in Highland and nearby Sharp County areas.',
    city: 'Highland',
    state: 'AR',
    county: 'Sharp County',
    roadMiles: 72,
    driveMinutes: 100,
    nearby: ['ash-flat-ar', 'imboden-ar', 'pocahontas-ar', 'walnut-ridge-ar'],
  },
  {
    slug: 'ash-flat-ar',
    title: 'Ash Flat, AR (Sharp County)',
    description: 'Portable storage delivery for moves and remodels in Ash Flat.',
    city: 'Ash Flat',
    state: 'AR',
    county: 'Sharp County',
    roadMiles: 78,
    driveMinutes: 105,
    nearby: ['highland-ar', 'imboden-ar', 'batesville-ar', 'pocahontas-ar'],
  },
  {
    slug: 'maynard-ar',
    title: 'Maynard, AR (Randolph County)',
    description: 'Portable storage for residential and business projects in Maynard.',
    city: 'Maynard',
    state: 'AR',
    county: 'Randolph County',
    roadMiles: 52,
    driveMinutes: 68,
    nearby: ['pocahontas-ar', 'delaplaine-ar', 'corning-ar', 'imboden-ar'],
  },
  {
    slug: 'corning-ar',
    title: 'Corning, AR (Clay County)',
    description: 'Portable storage delivery for moves, renovation jobs, and cleanup projects in Corning.',
    city: 'Corning',
    state: 'AR',
    county: 'Clay County',
    roadMiles: 28,
    driveMinutes: 43,
    nearby: ['delaplaine-ar', 'maynard-ar', 'marmaduke-ar', 'rector-ar'],
  },
  {
    slug: 'imboden-ar',
    title: 'Imboden, AR (Lawrence County)',
    description: 'Portable storage options for homes and projects in Imboden.',
    city: 'Imboden',
    state: 'AR',
    county: 'Lawrence County',
    roadMiles: 45,
    driveMinutes: 60,
    nearby: ['pocahontas-ar', 'walnut-ridge-ar', 'highland-ar', 'maynard-ar'],
  },
  {
    slug: 'batesville-ar',
    title: 'Batesville, AR (Independence County)',
    description: 'Portable storage delivery for moves, remodels, and storage overflow in Batesville.',
    city: 'Batesville',
    state: 'AR',
    county: 'Independence County',
    roadMiles: 94,
    driveMinutes: 122,
    nearby: ['newport-ar', 'swifton-ar', 'ash-flat-ar', 'bald-knob-ar'],
  },
  {
    slug: 'bald-knob-ar',
    title: 'Bald Knob, AR (White County)',
    description: 'Portable storage for household and business projects in Bald Knob.',
    city: 'Bald Knob',
    state: 'AR',
    county: 'White County',
    roadMiles: 95,
    driveMinutes: 106,
    nearby: ['searcy-ar', 'newport-ar', 'batesville-ar', 'swifton-ar'],
  },
  {
    slug: 'searcy-ar',
    title: 'Searcy, AR (White County)',
    description: 'Portable storage delivery for homes and commercial projects in Searcy.',
    city: 'Searcy',
    state: 'AR',
    county: 'White County',
    roadMiles: 106,
    driveMinutes: 119,
    nearby: ['bald-knob-ar', 'newport-ar', 'batesville-ar', 'swifton-ar'],
  },
  {
    slug: 'newport-ar',
    title: 'Newport, AR (Jackson County)',
    description: 'Portable storage options for projects in Newport and the surrounding area.',
    city: 'Newport',
    state: 'AR',
    county: 'Jackson County',
    roadMiles: 68,
    driveMinutes: 80,
    nearby: ['swifton-ar', 'batesville-ar', 'cash-ar', 'bald-knob-ar'],
  },
]

export const faqItems = [
  {
    question: 'What size portable storage container do I need?',
    answer:
      'Our containers come in 2 sizes: 8\' x 16\' x 8\' and 8\' x 20\' x 8\'. The right size depends on whether you are storing a few rooms of furniture, an entire house, or just overflow items. Start with the volume of the largest rooms and leave room for walkways and stackable boxes.',
  },
  {
    question: 'How does delivery work?',
    answer:
      'We schedule a delivery date, bring the container to your driveway or preferred spot, and pick it up when you are finished.',
  },
  {
    question: 'Will you relocate a container after delivery?',
    answer:
      'Yes. We offer container relocation as a service. Contact our office for further details.',
  },
  {
    question: 'Do you serve areas outside Northeast Arkansas?',
    answer:
      'Yes. We serve Paragould, Northeast Arkansas, and surrounding communities. If you are interested in the services we offer, contact us and we can confirm availability.',
  },
  {
    question: 'How much does portable storage cost?',
    answer:
      'For up-to-date pricing, refer to our <a href="{{reserveUrl}}">Reservation Page</a>. Pricing usually depends on container size, rental length, and delivery distance. Ask for a quote that separates container rental from delivery and pickup so you can compare accurately.',
  },
  {
    question: 'Can I keep the container at my home?',
    answer:
      'Yes. On-site storage is a common use case because it keeps your belongings close and easy to access while you pack, move, or remodel.',
  },
  {
    question: 'How secure is a portable storage container?',
    answer:
      'Portable containers are built from heavy-duty steel and can be secured with your own padlock for added protection.',
  },
  {
    question: 'How long can I keep the container?',
    answer:
      'Rental periods are flexible, so you can keep the container for a short move or a longer renovation project.',
  },
  {
    question: 'What can I store in the container?',
    answer:
      'Most household goods, furniture, boxes, tools, and business supplies are suitable. If you are concerned about storing a potentially hazardous material, please contact our office.',
  },
  {
    question: 'Can I access my belongings while the container is on-site?',
    answer:
      'Yes. One of the main advantages of on-site portable storage is that you can get to your items whenever you need them.',
  },
  {
    question: 'How do I reserve a container?',
    answer:
      'Call our office or use the reserve link on the website. We will help you choose the right container and schedule delivery.',
  },
] as const

export const trustFacts = [
  'Local business located in Paragould, Arkansas',
  'Owner has deep roots in the community and construction industry',
  'Serving North East Arkansas and surrounding communities since 2017',
  'Inspecting and cleaning containers before delivery',
] as const

export const testimonials = [
  {
    quote: 'Great place and great people... very friendly and go above and beyond to help you.',
    name: 'Shawn S.',
    location: 'Jonesboro, AR',
    useCase: 'Personal Storage',
    image: '/images/customers/shawn-s.png',
  },
  {
    quote: 'They made my move easy, and they moved my stuff in a timely manner. Thanks Liddell StorAll!',
    name: 'James O.',
    location: 'Pocahontas, AR',
    useCase: 'Local Move',
    image: '/images/customers/john-o.jpg',
  },
  {
    quote: 'Liddell Stor All’s staff is personal and professional. I’ve had such a smooth experience with them and have known my things are safe and secure.',
    name: 'Hannah R.',
    location: 'Benton, AR',
    useCase: 'Personal Storage',
    image: '/images/customers/hannah-r.png',
  },
] as const
